### ISSUE TITLE
Rename temporary.less with dark-mode.less

### ISSUE THREAD

**Issue by marc-farre** [felixhahnweilheim/humhub-dark-mode#13]
When analyzing style with the browser developer tools, we have:
![image](https://github.com/felixhahnweilheim/humhub-dark-mode/assets/23310825/cb4cfb71-4a7f-4a9d-a0cb-afbd23a7e7db)

If think it would be better to display `dark-mode.less` instead of `temporary.less`

**Comment by felixhahnweilheim** [comment]
Actually I named the file temporary.less because it is removed after the CSS has been built. (It is a workaround for the css-color-extractor to re-add the CSS variables.)

 I don't really understand why the browser is showing a file that does not exist anymore (and is not mentioned in the HTML). Probably it takes the information from the last CSS line mentioning the source LESS file.

So do you think we should rename the temporary file to dark-mode.less ?

**Comment by marc-farre** [comment]
The info is in `theme.css.map` which is created with this command:
```sh
lessc less/build2.less css/theme.css --clean-css="--s1 --advanced" --source-map=css/theme.css.map
```

Yes, I suggest to rename it to `dark-mode.less`

**Comment by felixhahnweilheim** [comment]
@marc-farre What do you think about removing the CSS map?  
So the browser would just show `theme.css` or `dark.css`.

In the case of the dark themes the CSS is not usefull because the temporary.less file is actually already a compiled CSS file.

**Comment by marc-farre** [comment]
Yes, good idea.
