### ISSUE TITLE
New option: always light theme by default

### ISSUE THREAD

**Issue by punkyard** [felixhahnweilheim/humhub-dark-mode#50]
hi
when dark theme is installed, we have a nice switch in the middle of the menu top, which allows people to choose which mode they prefer. But also once the module is installed, by default, the home page is shown in the dark mode.

it would be nice to be able to set this switch to a default position in order to keep the home page bright AND offer the possibility to switch to dark.

Finally, using the switch on home page for a user that's not logged in, drives to loggin page. Which is not the result we expected.

Thanks a lot for your concern and if can make it evolve ✌️

**Comment by felixhahnweilheim** [comment]
Dear @punkyard thanks for reporting the bug when logged out. I have created a seperate issue and will look into it.

By default the system setting is selected. So only if your browser/device is in dark mode you will have it dark.
This is the expected behaviour for me.
Of course I would be open to a pull request that introduces a new configuration option.

**Comment by punkyard** [comment]
Thanks for your concern @felixhahnweilheim
